# Municipality Data EDA

In [2]:
# Imports 
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import glob
import os
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
%matplotlib inline

In [3]:
def loaddata(path):
    """
    load the data
    """ 
    path = path
    all_files = glob.glob(os.path.join(path, "*.csv"))
    data = []
    df = pd.DataFrame()
    for fil in all_files:
        dataload = pd.read_csv(fil,skipinitialspace=True)
        data.append(dataload)
    return data

In [18]:
def wrangle_youth(data):
    """
    Wrangle municipal data
    """
    
    data = data.set_index('financial_year_end.year')
    data.drop(" ")
    data.index.name = None
    
    
    '    ======== Uncomment section not being used to clean data below =====================    '
    
    # ------- Use this for income expenditure, repair and maintanace, cash flow data use for balance sheet ------
    
    data.drop([ 'amount_type.label', 'item.code', 'financial_period.period','item.composition',
            'item.position_in_return_form','period_length.length','item.return_form_structure'],1, inplace=True)

    data.columns = ['total_amount','account_type','mun_code','mun_name', 'label']
    
    
    #------------------------------------ Use it for debitor -----------------------------------
        
    data.drop(['amount_type.label','item.code', 'financial_period.period','item.composition',
            'item.position_in_return_form','period_length.length','item.return_form_structure','l60_amount.sum',
           'g1_amount.sum', 'l30_amount.sum','l180_amount.sum', 'l150_amount.sum', 'l1_amount.sum',
        'l120_amount.sum', 'l90_amount.sum','customer_group.code','badi_amount.sum','bad_amount.sum']
        ,1, inplace=True)

    data.columns  = ['mun_name','mun_code', 'account_type','label','total_amount']
    

  
     # ------------------ Use this for wasteful expenditure data ----------------------------------------------
    
    data.columns = [ 'mun_name','mun_code','item.code', 'label','total_amount']
    data.drop("item.code",1, inplace=True)
    

    
    return data

In [6]:
# Path to files
path16 = '/home/dside/Documents/Csir_project/EDA/Municipal/2016 ' 
path15 = '/home/dside/Documents/Csir_project/EDA/Municipal/2015 ' 
path14 = '/home/dside/Documents/Csir_project/EDA/Municipal/2014 ' 
path13 = '/home/dside/Documents/Csir_project/EDA/Municipal/2013 ' 

#path = "/home/dside/Documents/Csir_project/EDA/Youth jupyter"

# Load different file and merge them for each catagory

In [7]:
# Merge the dataframe into a time series.

df13 = loaddata(path13)[0]
df14 = loaddata(path14)[0]
df15 = loaddata(path15)[0]
df16 = loaddata(path16)[0]

df0 = pd.concat([df13,df14,df15,df16])

df13 = loaddata(path13)[1]
df14 = loaddata(path14)[1]
df15 = loaddata(path15)[1]
df16 = loaddata(path16)[1]

df1 = pd.concat([df13,df14,df15,df16])

df13 = loaddata(path13)[2]
df14 = loaddata(path14)[2]
df15 = loaddata(path15)[2]
df16 = loaddata(path16)[2]

df2 = pd.concat([df13,df14,df15,df16])

df13 = loaddata(path13)[3]
df14 = loaddata(path14)[3]
df15 = loaddata(path15)[3]


df3 = pd.concat([df13,df14,df15])

df13 = loaddata(path13)[4]
df14 = loaddata(path14)[4]
df15 = loaddata(path15)[4]
df16 = loaddata(path16)[4]

df4 = pd.concat([df13,df14,df15,df16])

df13 = loaddata(path13)[5]
df14 = loaddata(path14)[5]
df15 = loaddata(path15)[5]
#df16 = loaddata(path16)[5]

df5 = pd.concat([df13,df14,df15])

df13 = loaddata(path13)[6]
df14 = loaddata(path14)[6]
df15 = loaddata(path15)[6]

df6 = pd.concat([df13,df14,df15])

# Income Expenditure, Repair and Maintanace, Cash flow  and Balance sheet

Make a time series of the data and remove unwanted columns

In [9]:
df_IncoExpe = wrangle_youth(df0)
df_CasFlo = wrangle_youth(df1)
df_RepMianta = wrangle_youth(df2)
df_balancesheet = wrangle_youth(df6)

df_IncoExpe.to_csv("/home/dside/Documents/Csir_project/EDA/Municipal/Income_and_Expenditure.csv")
df_CasFlo.to_csv("/home/dside/Documents/Csir_project/EDA/Municipal/cash_flow.csv")
df_RepMianta.to_csv("/home/dside/Documents/Csir_project/EDA/Municipal/repair_maintance.csv")
df_balancesheet.to_csv("/home/dside/Documents/Csir_project/Output/Balancesheet.csv")

# Credit and Debit 
Make a time series of the data and remove unwanted columns

In [12]:
df_aged_creditor = wrangle_youth(df4)
df_debtor = wrangle_youth(df5)

df_debtor.to_csv("/home/dside/Documents/Csir_project/Output/debitor.csv")
df_aged_creditor.to_csv("/home/dside/Documents/Csir_project/Output/Creditor.csv")

# Wasteful Expenditure
Make a time series of the data and remove unwanted columns

In [14]:
df_Wastefulexpense = wrangle_youth(df3)
df_Wastefulexpense.to_csv("/home/dside/Documents/Csir_project/Output/Wasteful_expenditure.csv")

In [321]:
# All the data
df_IncoExpe
df_CasFlo 
df_RepMianta 
df_balancesheet 
df_aged_creditor 
df_debtor 
df_Wastefulexpense

               mun_name mun_code         label  total_amount
2013       Buffalo City      BUF     fruitless  8.080000e+06
2013       Buffalo City      BUF     irregular  1.171280e+08
2013       Buffalo City      BUF  unauthorised  1.447800e+07
2013  City of Cape Town      CPT     fruitless           NaN
2013  City of Cape Town      CPT     irregular  1.465000e+06
2013  City of Cape Town      CPT  unauthorised           NaN
2013         West Coast      DC1     fruitless  0.000000e+00
2013         West Coast      DC1     irregular  0.000000e+00
2013         West Coast      DC1  unauthorised  0.000000e+00
2013             Cacadu     DC10     fruitless           NaN
2013             Cacadu     DC10     irregular  7.894000e+06
2013             Cacadu     DC10  unauthorised           NaN
2013           Amathole     DC12     fruitless  5.869500e+07
2013           Amathole     DC12     irregular  2.147000e+06
2013           Amathole     DC12  unauthorised  5.869500e+07
2013         Chris Hani     DC13     fruitless  8.170000e+05
2013         Chris Hani     DC13     irregular  4.295900e+07
2013         Chris Hani     DC13  unauthorised  2.301000e+06
2013          Joe Gqabi     DC14     fruitless  4.360000e+06
2013          Joe Gqabi     DC14     irregular  4.220000e+05
2013          Joe Gqabi     DC14  unauthorised  3.938000e+06
2013          O.R.Tambo     DC15     fruitless  1.513400e+07
2013          O.R.Tambo     DC15     irregular  2.641970e+08
2013          O.R.Tambo     DC15  unauthorised  9.181000e+06
2013            Xhariep     DC16     fruitless  1.330000e+05
2013            Xhariep     DC16     irregular  1.777400e+07
2013            Xhariep     DC16  unauthorised  1.115100e+07
2013      Lejweleputswa     DC18     fruitless  2.886800e+08
2013      Lejweleputswa     DC18     irregular  3.124300e+07
2013      Lejweleputswa     DC18  unauthorised  1.595540e+09
...                 ...      ...           ...           ...
2015          Kannaland    WC041     fruitless  7.035600e+04
2015          Kannaland    WC041     irregular  8.532194e+06
2015          Kannaland    WC041  unauthorised  3.281391e+07
2015           Hessequa    WC042     fruitless  7.550600e+05
2015           Hessequa    WC042     irregular  1.364088e+07
2015           Hessequa    WC042  unauthorised  8.545526e+06
2015         Mossel Bay    WC043     fruitless           NaN
2015         Mossel Bay    WC043     irregular  2.279942e+06
2015         Mossel Bay    WC043  unauthorised  2.130700e+04
2015             George    WC044     fruitless           NaN
2015             George    WC044     irregular  1.224100e+04
2015             George    WC044  unauthorised  4.353544e+07
2015         Oudtshoorn    WC045     fruitless  4.070213e+06
2015         Oudtshoorn    WC045     irregular  1.107902e+08
2015         Oudtshoorn    WC045  unauthorised  9.524877e+07
2015              Bitou    WC047     fruitless  2.622000e+05
2015              Bitou    WC047     irregular  4.507500e+04
2015              Bitou    WC047  unauthorised           NaN
2015             Knysna    WC048     fruitless  1.253100e+04
2015             Knysna    WC048     irregular           NaN
2015             Knysna    WC048  unauthorised  2.205698e+07
2015         Laingsburg    WC051     fruitless  6.490900e+04
2015         Laingsburg    WC051     irregular  3.102546e+07
2015         Laingsburg    WC051  unauthorised  2.367510e+07
2015      Prince Albert    WC052     fruitless           NaN
2015      Prince Albert    WC052     irregular  7.990065e+06
2015      Prince Albert    WC052  unauthorised  7.510900e+04
2015      Beaufort West    WC053     fruitless  1.596700e+05
2015      Beaufort West    WC053     irregular  1.587173e+07
2015      Beaufort West    WC053  unauthorised  2.848795e+07

[2499 rows x 4 columns]

In [15]:
# fill in the missing values with zero
df_RepMianta= df_RepMianta.fillna(0) 
df_Wastefulexpense = df_Wastefulexpense.fillna(0) 
df_RepMianta

,total_amount,account_type,mun_code,mun_name,label
2013,0.000000e+00,AUDA,BUF,Buffalo City,Employee Related Costs
2013,0.000000e+00,AUDA,BUF,Buffalo City,Other Materials
2013,0.000000e+00,AUDA,BUF,Buffalo City,Contracted Services
2013,2.637019e+08,AUDA,BUF,Buffalo City,Other Expenditure
2013,2.637019e+08,AUDA,BUF,Buffalo City,Total Repairs and Maintenance Expenditure
2013,1.030137e+09,AUDA,CPT,City of Cape Town,Employee Related Costs
2013,2.026456e+08,AUDA,CPT,City of Cape Town,Other Materials
2013,1.314473e+09,AUDA,CPT,City of Cape Town,Contracted Services
2013,2.091730e+08,AUDA,CPT,City of Cape Town,Other Expenditure
2013,2.756429e+09,AUDA,CPT,City of Cape Town,Total Repairs and Maintenance Expenditure
2013,0.000000e+00,AUDA,DC1,West Coast,Employee Related Costs
2013,2.588166e+07,AUDA,DC1,West Coast,Other Materials
2013,0.000000e+00,AUDA,DC1,West Coast,Contracted Services
2013,0.000000e+00,AUDA,DC1,West Coast,Other Expenditure
2013,2.588166e+07,AUDA,DC1,West Coast,Total Repairs and Maintenance Expenditure
2013,0.000000e+00,AUDA,DC10,Cacadu,Employee Related Costs
2013,0.000000e+00,AUDA,DC10,Cacadu,Other Materials
2013,0.000000e+00,AUDA,DC10,Cacadu,Contracted Services
2013,3.881290e+05,AUDA,DC10,Cacadu,Other Expenditure
2013,3.881290e+05,AUDA,DC10,Cacadu,Total Repairs and Maintenance Expenditure
2013,0.000000e+00,AUDA,DC12,Amathole,Employee Related Costs
2013,0.000000e+00,AUDA,DC12,Amathole,Other Materials
2013,0.000000e+00,AUDA,DC12,Amathole,Contracted Services
2013,0.000000e+00,AUDA,DC12,Amathole,Other Expenditure
2013,0.000000e+00,AUDA,DC12,Amathole,Total Repairs and Maintenance Expenditure
2013,0.000000e+00,AUDA,DC13,Chris Hani,Employee Related Costs
2013,0.000000e+00,AUDA,DC13,Chris Hani,Other Materials
2013,0.000000e+00,AUDA,DC13,Chris Hani,Contracted Services
2013,1.746150e+06,AUDA,DC13,Chris Hani,Other Expenditure
2013,1.746150e+06,AUDA,DC13,Chris Hani,Total Repairs and Maintenance Expenditure
...,...,...,...,...,...
2016,0.000000e+00,AUDA,WC045,Oudtshoorn,Employee Related Costs
2016,0.000000e+00,AUDA,WC045,Oudtshoorn,Other Materials
2016,0.000000e+00,AUDA,WC045,Oudtshoorn,Contracted Services
2016,9.009288e+06,AUDA,WC045,Oudtshoorn,Other Expenditure
2016,9.009288e+06,AUDA,WC045,Oudtshoorn,Total Repairs and Maintenance Expenditure
2016,0.000000e+00,AUDA,WC047,Bitou,Employee Related Costs
2016,0.000000e+00,AUDA,WC047,Bitou,Other Materials
2016,0.000000e+00,AUDA,WC047,Bitou,Contracted Services
2016,0.000000e+00,AUDA,WC047,Bitou,Other Expenditure
2016,0.000000e+00,AUDA,WC047,Bitou,Total Repairs and Maintenance Expenditure
2016,0.000000e+00,AUDA,WC048,Knysna,Employee Related Costs
2016,0.000000e+00,AUDA,WC048,Knysna,Other Materials
2016,0.000000e+00,AUDA,WC048,Knysna,Contracted Services
2016,0.000000e+00,AUDA,WC048,Knysna,Other Expenditure
2016,0.000000e+00,AUDA,WC048,Knysna,Total Repairs and Maintenance Expenditure
2016,0.000000e+00,AUDA,WC051,Laingsburg,Employee Related Costs
2016,0.000000e+00,AUDA,WC051,Laingsburg,Other Materials
2016,0.000000e+00,AUDA,WC051,Laingsburg,Contracted Services
2016,0.000000e+00,AUDA,WC051,Laingsburg,Other Expenditure
2016,0.000000e+00,AUDA,WC051,Laingsburg,Total Repairs and Maintenance Expenditure
2016,0.000000e+00,AUDA,WC052,Prince Albert,Employee Related Costs
2016,0.000000e+00,AUDA,WC052,Prince Albert,Other Materials
2016,0.000000e+00,AUDA,WC052,Prince Albert,Contracted Services
2016,0.000000e+00,AUDA,WC052,Prince Albert,Other Expenditure
2016,0.000000e+00,AUDA,WC052,Prince Albert,Total Repairs and Maintenance Expenditure
2016,0.000000e+00,AUDA,WC053,Beaufort West,Employee Related Costs
2016,0.000000e+00,AUDA,WC053,Beaufort West,Other Materials
2016,0.000000e+00,AUDA,WC053,Beaufort West,Contracted Services
2016,0.000000e+00,AUDA,WC053,Beaufort West,Other Expenditure
2016,0.000000e+00,AUDA,WC053,Beaufort West,Total Repairs and Maintenance Expenditure

In [246]:
yr

['2013', '2014', '2015', '2016']

In [255]:

def f(yr1,yr2):
    data =df_CasFlo.loc[yr1:yr2]
    data.plot(kind='hist',bins=10)

interact(f,yr1 =yr,yr2=yr);
# df_incexp = wrangle_youth(df0)
# df_cashflow = wrangle_youth(df1)
# df_repamain = wrangle_youth(df2)

# #----------

# df_uifwexp = wrangle_youth(df3)

# #-----------
# df_aged_creditor = wrangle_youth(df4)
# df_debtor = wrangle_youth(df5)
# df_balancesheet = wrangle_youth(df6)

A Jupyter Widget