# Municipality Data EDA

In [97]:
# Imports 
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import os
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
%matplotlib inline

In [98]:
def loaddata(path):
    """
    load the data
    """ 
    path = path
    all_files = glob.glob(os.path.join(path, "*.csv"))
    data = []
    df = pd.DataFrame()
    for fil in all_files:
        dataload = pd.read_csv(fil,skipinitialspace=True)
        data.append(dataload)
    return data

In [18]:
def wrangle_youth(data):
    """
    Wrangle municipal data
    """
    
    data = data.set_index('financial_year_end.year')
    data.drop(" ")
    data.index.name = None
    
    
    '    ======== Uncomment section not being used to clean data below =====================    '
    
    # ------- Use this for income expenditure, repair and maintanace, cash flow data use for balance sheet ------
    
    data.drop([ 'amount_type.label', 'item.code', 'financial_period.period','item.composition',
            'item.position_in_return_form','period_length.length','item.return_form_structure'],1, inplace=True)

    data.columns = ['total_amount','account_type','mun_code','mun_name', 'label']
    
    
    #------------------------------------ Use it for debitor -----------------------------------
        
    data.drop(['amount_type.label','item.code', 'financial_period.period','item.composition',
            'item.position_in_return_form','period_length.length','item.return_form_structure','l60_amount.sum',
           'g1_amount.sum', 'l30_amount.sum','l180_amount.sum', 'l150_amount.sum', 'l1_amount.sum',
        'l120_amount.sum', 'l90_amount.sum','customer_group.code','badi_amount.sum','bad_amount.sum']
        ,1, inplace=True)

    data.columns  = ['mun_name','mun_code', 'account_type','label','total_amount']
    

  
     # ------------------ Use this for wasteful expenditure data ----------------------------------------------
    
    data.columns = [ 'mun_name','mun_code','item.code', 'label','total_amount']
    data.drop("item.code",1, inplace=True)
    

    
    return data

In [84]:
def Filter(data, text, Column):
    """
    Filters table 
    
    text: what you want to filter with
    Column: Column you want to filter in
    """
    word_filter = text
    Column = Column
    data = data[data[Column].str.contains(word_filter, na = False)]
    
    return data

In [6]:
# Path to files
path16 = '/home/dside/Documents/Csir_project/EDA/Municipal/2016 ' 
path15 = '/home/dside/Documents/Csir_project/EDA/Municipal/2015 ' 
path14 = '/home/dside/Documents/Csir_project/EDA/Municipal/2014 ' 
path13 = '/home/dside/Documents/Csir_project/EDA/Municipal/2013 ' 

#path = "/home/dside/Documents/Csir_project/EDA/Youth jupyter"

#  SEC:1                Load ing and Merging of file across the years

In [7]:
# Merge the dataframe into a time series.

df13 = loaddata(path13)[0]
df14 = loaddata(path14)[0]
df15 = loaddata(path15)[0]
df16 = loaddata(path16)[0]

df0 = pd.concat([df13,df14,df15,df16])

df13 = loaddata(path13)[1]
df14 = loaddata(path14)[1]
df15 = loaddata(path15)[1]
df16 = loaddata(path16)[1]

df1 = pd.concat([df13,df14,df15,df16])

df13 = loaddata(path13)[2]
df14 = loaddata(path14)[2]
df15 = loaddata(path15)[2]
df16 = loaddata(path16)[2]

df2 = pd.concat([df13,df14,df15,df16])

df13 = loaddata(path13)[3]
df14 = loaddata(path14)[3]
df15 = loaddata(path15)[3]


df3 = pd.concat([df13,df14,df15])

df13 = loaddata(path13)[4]
df14 = loaddata(path14)[4]
df15 = loaddata(path15)[4]
df16 = loaddata(path16)[4]

df4 = pd.concat([df13,df14,df15,df16])

df13 = loaddata(path13)[5]
df14 = loaddata(path14)[5]
df15 = loaddata(path15)[5]
#df16 = loaddata(path16)[5]

df5 = pd.concat([df13,df14,df15])

df13 = loaddata(path13)[6]
df14 = loaddata(path14)[6]
df15 = loaddata(path15)[6]

df6 = pd.concat([df13,df14,df15])

# SEC: 2                     Data Wrangling

 Income Expenditure, Repair and Maintanace, Cash flow  and Balance sheet

In [9]:
df_IncoExpe = wrangle_youth(df0)
df_CasFlo = wrangle_youth(df1)
df_RepMianta = wrangle_youth(df2)
df_balancesheet = wrangle_youth(df6)

df_IncoExpe.to_csv("/home/dside/Documents/Csir_project/EDA/Municipal/Income_and_Expenditure.csv")
df_CasFlo.to_csv("/home/dside/Documents/Csir_project/EDA/Municipal/cash_flow.csv")
df_RepMianta.to_csv("/home/dside/Documents/Csir_project/EDA/Municipal/repair_maintance.csv")
df_balancesheet.to_csv("/home/dside/Documents/Csir_project/Output/Balancesheet.csv")

Creditor and Debitor data

In [12]:
df_aged_creditor = wrangle_youth(df4)
df_debtor = wrangle_youth(df5)

df_debtor.to_csv("/home/dside/Documents/Csir_project/Output/debitor.csv")
df_aged_creditor.to_csv("/home/dside/Documents/Csir_project/Output/Creditor.csv")

Wasteful Expenditure

In [14]:
df_Wastefulexpense = wrangle_youth(df3)
df_Wastefulexpense.to_csv("/home/dside/Documents/Csir_project/Output/Wasteful_expenditure.csv")

In [63]:
# fill in the missing values with zero
df_RepMianta= df_RepMianta.fillna(0) 
df_Wastefulexpense = df_Wastefulexpense.fillna(0)

In [258]:
n = 2
df_IncoExpe.head(n)
df_CasFlo.head(n)
df_RepMianta.head(n)
df_balancesheet.head(n)
df_aged_creditor.head(n)
df_Wastefulexpense.head(n)
df_debtor.head(n)

,mun_name,mun_code,account_type,label,total_amount,province
2013,Buffalo City,BUF,AUDA,Debtors Age Analysis By Income Source,0,KwaZulu-Natal
2013,Buffalo City,BUF,AUDA,Trade and Other Receivables from Exchange Tran...,272677143,KwaZulu-Natal

# SEC:3    Total of all goods and services for each  Municipality

We considered the total expenses of all good and services for each Municipality. And we also considered municipality 
per province.

In [681]:
df_Wastefulexpense
df_debtor_Total = Filter(df_debtor, 'Total', 'label')
df_RepMianta_Total = Filter(df_RepMianta, 'Total', 'label')
df_aged_creditor_Total  = Filter(df_aged_creditor, 'Total', 'label')
df_CasFlo_Total = Filter(df_CasFlo, 'Total', 'label')
df_IncoExpe_Total = Filter(df_IncoExpe, 'Total', 'label')
df_balancesheet_total = Filter(df_balancesheet, 'Total', 'label')
df_Wastefulexpense.to_csv("/home/dside/Documents/Csir_project/Output/Wasteful_Expenditure_total.csv")
df_debtor_Total.to_csv("/home/dside/Documents/Csir_project/Output/Debit_total.csv")
df_RepMianta_Total.to_csv("/home/dside/Documents/Csir_project/Output/Repair_Maintance_total.csv")
df_aged_creditor_Total .to_csv("/home/dside/Documents/Csir_project/Output/Age_creditor_total.csv")
df_CasFlo_Total.to_csv("/home/dside/Documents/Csir_project/Output/Cash_flow_total.csv")
df_IncoExpe_Total.to_csv("/home/dside/Documents/Csir_project/Output/Income_Expenditure_total.csv")

a = prov_link.loc[:,'Code'].tolist()
b = pd.DataFrame(prov_link[prov_link['Code'].str.contains('!', na = False)])['Code'].tolist()

for i in np.arange(len(a)):
    for j in np.arange(len(b)):
        if a[i] == b[j]:
            a[i] = b[j][6:]
            print a[i]
            
prov_link['Code'] = pd.DataFrame(a) 


prov_link.to_csv("/home/dside/Documents/Csir_project/Output/prov_link_NEW1.csv")

In [718]:
prov_link = pd.read_csv("/home/dside/Documents/Csir_project/Output/prov_link_NEW1.csv")

In [719]:
prov_link

,Unnamed: 0,Name,Code,Province
0,0,Buffalo City Metropolitan Municipality,BUF,Eastern Cape
1,1,City of Cape Town Metropolitan Municipality,CPT,Western Cape
2,2,City of Johannesburg Metropolitan Municipality,JHB,Gauteng
3,3,City of Tshwane Metropolitan Municipality,TSH,Gauteng
4,4,Ekurhuleni Metropolitan Municipality,EKU,Gauteng
5,5,eThekwini Metropolitan Municipality,ETH,KwaZulu-Natal
6,6,Mangaung Metropolitan Municipality,MAN,Free State
7,7,Nelson Mandela Bay Metropolitan Municipality,NMA,Eastern Cape
8,8,Alfred Nzo District Municipality,DC44,Eastern Cape
9,9,Amajuba District Municipality,DC25,KwaZulu-Natal
10,10,Amathole District Municipality,DC12,Eastern Cape
11,11,Bojanala District Municipality,DC37,North West
12,12,Cape Winelands District Municipality,DC2,Western Cape
13,13,Capricorn District Municipality,DC35,Limpopo
14,14,Central Karoo District Municipality,DC5,Western Cape
15,15,Chris Hani District Municipality,DC13,Eastern Cape
16,16,Dr Kenneth Kaunda District Municipality,DC40,North West
17,17,Dr Ruth Segomotsi Mompati District Municipality,DC39,North West
18,18,Eden District Municipality,DC4,Western Cape
19,19,Ehlanzeni District Municipality,DC32,Mpumalanga
20,20,Fezile Dabi District Municipality,DC20,Free State
21,21,Frances Baard District Municipality,DC9,Northern Cape
22,22,Gert Sibande District Municipality,DC30,Mpumalanga
23,23,Harry Gwala District Municipality,DC43,KwaZulu-Natal
24,24,iLembe District Municipality,DC29,KwaZulu-Natal
25,25,Joe Gqabi District Municipality,DC14,Eastern Cape
26,26,John Taolo Gaetsewe District Municipality,DC45,Northern Cape
27,27,King Cetshwayo District Municipality,DC28,KwaZulu-Natal
28,28,Lejweleputswa District Municipality,DC18,Free State
29,29,Mopani District Municipality,DC33,Limpopo
...,...,...,...,...
270,270,Nokeng tsa Taemane Local Municipality,GT461,Gauteng
271,271,Kungwini Local Municipality,GT462,Gauteng
272,272,Randfontein Local Municipality,GT482,Gauteng
273,273,Westonaria Local Municipality,GT483,Gauteng
274,274,Ezinqoleni Local Municipality,KZN215,KwaZulu-Natal
275,275,Hibiscus Coast Local Municipality,KZN216,KwaZulu-Natal
276,276,Vulamehlo Local Municipality,KZN211,KwaZulu-Natal
277,277,Emnambithi/Ladysmith Local Municipality,KZN232,KwaZulu-Natal
278,278,Indaka Local Municipality,KZN233,KwaZulu-Natal
279,279,Umtshezi Local Municipality,KZN234,KwaZulu-Natal
280,280,Imbabazane Local Municipality,KZN236,KwaZulu-Natal
281,281,Big 5 False Bay Local Municipality,KZN273,KwaZulu-Natal
282,282,Hlabisa Local Municipality,KZN274,KwaZulu-Natal
283,283,Ntambanana Local Municipality,KZN283,KwaZulu-Natal
284,284,Ingwe Local Municipality,KZN431,KwaZulu-Natal
285,285,Kwa Sani Local Municipality,KZN432,KwaZulu-Natal
286,286,Bohlabela District Municipality,CBDC4,Mpumalanga/Limpopo
287,287,Mutale Local Municipality,LIM342,Limpopo
288,288,Aganang Local Municipality,LIM352,Limpopo
289,289,Mookgopong Local Municipality,LIM364,Limpopo
290,290,Modimolle Local Municipality,LIM365,Limpopo
291,291,Fetakgomo Local Municipality,LIM474,Limpopo
292,292,Greater Tubatse Local Municipality,LIM475,Limpopo
293,293,Umjindi Local Municipality,MP323,Mpumalanga
294,294,Kagisano Local Municipality,NW391,North West
295,295,Molopo Local Municipality,NW395,North West
296,296,Ventersdorp Local Municipality,NW401,North West
297,297,Tlokwe Local Municipality,NW402,North West
298,298,Mier Local Municipality,NC081,Northern Cape
299,299,Khara Hais Local Municipality,NC083,Northern Cape

In [ ]:
a = prov_link.loc[:,'Code']
b = pd.DataFrame(prov_link[prov_link['Code'].str.contains('!', na = False)])['Code']

for i in np.arange(len(a)):
    for j in np.arange(len(b)):
        
        if a[i] == b[j]:
            a[i] = b[j][6:]
            print a[i]

In [581]:
# a = prov_link[prov_link.loc[i,'Code'].str.contains('!', na = False)]['Code']
# for i in range(prov_link.shape[0]):
#     for j in range(len(a)):
#         print  prov_link[prov_link.loc[j,'Code'].str.contains('!', na = False)]['Code']
    
    #print prov_link.loc[i,'Code'] == prov_link[prov_link.loc[j,'Code'].str.contains('!', na = False)]['Code']
    
#     if prov_link[i]  == prov_link[prov_link.loc[i,'Code'].str.contains('!', na = False)]['Code']:
#         print prov_link[i]

In [509]:
df_IncoExpe_Total[df_IncoExpe_Total.loc[:,"mun_code"] =="DC9"]

,total_amount,account_type,mun_code,mun_name,label
2013,101920686,AUDA,DC9,Frances Baard,Total Operating Revenue Generated
2013,101920686,AUDA,DC9,Frances Baard,Total Direct Operating Revenue
2013,0,AUDA,DC9,Frances Baard,Total Indirect Operating Revenue
2013,101920686,AUDA,DC9,Frances Baard,Total Operating Revenue
2013,99554980,AUDA,DC9,Frances Baard,Total Direct Operating Expenditure
2013,0,AUDA,DC9,Frances Baard,Total Indirect Operating Expenditure
2013,99554980,AUDA,DC9,Frances Baard,Total Operating Expenditure
2013,2365706,AUDA,DC9,Frances Baard,Operating Surplus / (Deficit) - Total Revenue ...
2014,102091472,AUDA,DC9,Frances Baard,Total Operating Revenue Generated
2014,102091472,AUDA,DC9,Frances Baard,Total Direct Operating Revenue
2014,0,AUDA,DC9,Frances Baard,Total Indirect Operating Revenue
2014,102091472,AUDA,DC9,Frances Baard,Total Operating Revenue
2014,102302541,AUDA,DC9,Frances Baard,Total Direct Operating Expenditure
2014,0,AUDA,DC9,Frances Baard,Total Indirect Operating Expenditure
2014,102302541,AUDA,DC9,Frances Baard,Total Operating Expenditure
2014,-211069,AUDA,DC9,Frances Baard,Operating Surplus / (Deficit) - Total Revenue ...
2015,110401519,AUDA,DC9,Frances Baard,Total Operating Revenue Generated
2015,110401519,AUDA,DC9,Frances Baard,Total Direct Operating Revenue
2015,0,AUDA,DC9,Frances Baard,Total Indirect Operating Revenue
2015,110401519,AUDA,DC9,Frances Baard,Total Operating Revenue
2015,112868897,AUDA,DC9,Frances Baard,Total Direct Operating Expenditure
2015,0,AUDA,DC9,Frances Baard,Total Indirect Operating Expenditure
2015,112868897,AUDA,DC9,Frances Baard,Total Operating Expenditure
2015,-2467378,AUDA,DC9,Frances Baard,Operating Surplus / (Deficit) - Total Revenue ...
2016,121058099,AUDA,DC9,Frances Baard,Total Operating Revenue Generated
2016,121058099,AUDA,DC9,Frances Baard,Total Direct Operating Revenue
2016,0,AUDA,DC9,Frances Baard,Total Indirect Operating Revenue
2016,121058099,AUDA,DC9,Frances Baard,Total Operating Revenue
2016,137554985,AUDA,DC9,Frances Baard,Total Direct Operating Expenditure
2016,0,AUDA,DC9,Frances Baard,Total Indirect Operating Expenditure
2016,137554985,AUDA,DC9,Frances Baard,Total Operating Expenditure
2016,-16496886,AUDA,DC9,Frances Baard,Operating Surplus / (Deficit) - Total Revenue ...

In [725]:
    
def Province_match(data1,data2):
    
        """
        Match each municipality to a province
        """
        
        data1 = data1.reset_index()
        prov = []
        c = 0.0

        for i in np.arange(data1.shape[0]):

            for j in np.arange(data2.shape[0]):


                 if data1.loc[i,"mun_code"] == data2.loc[j,"Code"]:
                    prov.append(data2.loc[j,"Province"])
                    

            
        data = pd.DataFrame(prov)
        print (data.shape)
        data1['Province'] = data
        data1 = data1.set_index('index')
        data1.index.name = None
       
        return data1

In [726]:
l = Province_match(df_balancesheet_total,prov_link)

(5838, 1)

In [729]:
# Match each municipality with the provinces

df_Wastefulexpense = Province_match(df_Wastefulexpense,prov_link)
df_debtor_Total = Province_match(df_debtor_Total,prov_link)
df_RepMianta_Total = Province_match(df_RepMianta_Total,prov_link)
df_aged_creditor_Total  = Province_match(df_aged_creditor_Total,prov_link)
df_CasFlo_Total = Province_match(df_CasFlo_Total,prov_link)
df_IncoExpe_Total = Province_match(df_IncoExpe_Total,prov_link)

(2508, 1)
(1492, 1)
(1121, 1)
(1118, 1)
(2112, 1)
(8464, 1)

In [730]:
df_Wastefulexpense.to_csv("/home/dside/Documents/Csir_project/Output/Wasteful_Expenditure_total.csv")
df_debtor_Total.to_csv("/home/dside/Documents/Csir_project/Output/Debit_total.csv")
df_RepMianta_Total.to_csv("/home/dside/Documents/Csir_project/Output/Repair_Maintance_total.csv")
df_aged_creditor_Total .to_csv("/home/dside/Documents/Csir_project/Output/Age_creditor_total.csv")
df_CasFlo_Total.to_csv("/home/dside/Documents/Csir_project/Output/Cash_flow_total.csv")
df_IncoExpe_Total.to_csv("/home/dside/Documents/Csir_project/Output/Income_Expenditure_total.csv")

In [325]:
# How much is each municipality spending 

#df_Wastefulexpense.groupby(['label','Province']).mean()
df_Wastefulexpense.groupby(df_Wastefulexpense.Province)